### ISSUE TITLE
BUG: Fix error not shown upon global load

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopyo#122]
Print error in these cases: 

https://github.com/shopyo/shopyo/blob/eb927cf223a1441df8fe3b98b427b168fffa403e/shopyo/app.py#L170

https://github.com/shopyo/shopyo/blob/eb927cf223a1441df8fe3b98b427b168fffa403e/shopyo/app.py#L204

In the format:

```
print('[ ] error loading template variable', e)
```

For all errors

**Comment by sanmay321** [comment]
@Abdur-rahmaanJ hey I would like to work on this issue .. assign me, please.
