### ISSUE TITLE
FIX(first-timers): Fix contributing link

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopyo#133]
Change the contributing link found [here](https://github.com/shopyo/shopyo/blob/146e6493ff921954156e0f28b131ddcd68511b82/README.md?plain=1#L21) to https://shopyo.readthedocs.io/en/latest/contrib.html

**Comment by lokeshvasnik** [comment]
let me try

**Comment by Abdur-rahmaanJ** [comment]
:heavy_check_mark: Assigned!
:small_airplane: You are good to go!
