### ISSUE TITLE
FIX(first-timers): Change the have a go section code

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopyo#134]
Change the have a go [section code](https://github.com/shopyo/shopyo/blob/146e6493ff921954156e0f28b131ddcd68511b82/README.md?plain=1#L32) to this:

<pre>
```bash
pip install shopyo==4.4.3
mkdir blog
cd blog
shopyo new -m # add default modules
shopyo run
```
</pre>

**Comment by anvikshik** [comment]
I would like to fix this one.

**Comment by Abdur-rahmaanJ** [comment]
@anvikshik 
:heavy_check_mark: Assigned
:small_airplane: You can tackle the issue!
