### ISSUE TITLE
`shopyo initialise` is broken

### ISSUE THREAD

**Issue by AndrejGorodnij** [shopyo/shopyo#144]
I got an error, when try to run you project by README documentation.

`shopyo initialise` command returns:

`/venv/lib/python3.11/site-packages/shopyo/api/cmd_helper.py", line 56, in _clean
    db.engine.execute("DROP TABLE IF EXISTS alembic_version;")`

**Comment by Abdur-rahmaanJ** [comment]
@AndrejGorodnij Your SQLAlchemy version is? Also can you return the full traceback? Thanks

Also, what db are you using?

**Comment by Abdur-rahmaanJ** [comment]
Try installing `pip install pip install SQLAlchemy==1.4.49`

**Comment by Abdur-rahmaanJ** [comment]
Also fixed in 4.9.0, try it.

**Comment by AndrejGorodnij** [comment]
I will try, thanks

**Comment by AndrejGorodnij** [comment]
Yes, 4.9.0 version fix that. I think README need an update, so many people fucked up with `pip install shopyo==4.4.3`, and just go away

**Comment by Abdur-rahmaanJ** [comment]
@AndrejGorodnij Thanks 100%
