### ISSUE TITLE
Shopyo is not working on Python 3.11

### ISSUE THREAD

**Issue by kuslahne** [shopyo/shopyo#208]
Hi Abdur-Rahmaan,

Thank you for create this framework. I just tried your framework running on Python 3.11 and NixOs with virtualenv. I followed your documentation, it can run webserver but endpoint for /index is not found and admin also is not working.

Endpoint                             Methods    Rule                                               
-----------------------------------  ---------  ---------------------------------------------------
admin.index                          GET        /admin/                                            
admin.indexs                         GET        /admin/dashboard                                   
admin.static                         GET        /admin/static/<path:filename>                      
devstatic                            GET        /devstatic/<path:boxormodule>/f/<path:path>        
i18n.index                           GET        /shopyo-i18n/                                      
i18n.set_lang                        GET        /shopyo-i18n/set-lang                              
shopyo_appadmin.admin_delete         GET        /shopyo-appadmin/delete/<id>                       
shopyo_appadmin.admin_edit           GET        /shopyo-appadmin/edit/<id>                         
shopyo_appadmin.admin_update         POST       /shopyo-appadmin/update                            
shopyo_appadmin.roles                GET        /shopyo-appadmin/roles                             
shopyo_appadmin.roles_add            POST       /shopyo-appadmin/roles/add                         
shopyo_appadmin.roles_delete         GET        /shopyo-appadmin/roles/<role_id>/delete            
shopyo_appadmin.roles_update         POST       /shopyo-appadmin/roles/update                      
shopyo_appadmin.user_add             GET, POST  /shopyo-appadmin/add                               
shopyo_appadmin.user_list            GET        /shopyo-appadmin/                                  
shopyo_auth.confirm                  GET        /shopyo-auth/confirm/<token>                       
shopyo_auth.login                    GET, POST  /shopyo-auth/login                                 
shopyo_auth.logout                   GET        /shopyo-auth/logout                                
shopyo_auth.register                 GET, POST  /shopyo-auth/register                              
shopyo_auth.resend                   GET        /shopyo-auth/resend                                
shopyo_auth.unconfirmed              GET        /shopyo-auth/unconfirmed                           
shopyo_base.index                    GET        /shopyo-base/                                      
shopyo_dashboard.index               GET        /shopyo-dashboard/                                 
shopyo_page.check_pagecontent        GET, POST  /shopyo-page/check_pagecontent                     
shopyo_page.dashboard                GET        /shopyo-page/dashboard                             
shopyo_page.edit_pagecontent         GET, POST  /shopyo-page/edit_pagecontent                      
shopyo_page.index                    GET        /shopyo-page/dashboard/all-pages                   
shopyo_page.index_all                GET        /shopyo-page/dashboard/all                         
shopyo_page.view_page                GET        /shopyo-page/s/<slug>                              
shopyo_page.view_page_dashboard      GET        /shopyo-page/dashboard/s/<slug>                    
shopyo_theme.activate_back_theme     GET        /shopyo-theme/activate/back/<theme_name>           
shopyo_theme.activate_front_theme    GET        /shopyo-theme/activate/front/<theme_name>          
shopyo_theme.active_back_theme_css   GET        /shopyo-theme/theme/back/<active_theme>/styles.css 
shopyo_theme.active_front_theme_css  GET        /shopyo-theme/theme/front/<active_theme>/styles.css
shopyo_theme.index                   GET        /shopyo-theme/                                     
static                               GET        /static/<path:filename>    

It said on console:
ERROR in app: Exception on /shopyo-auth/login [GET]

![image](https://github.com/user-attachments/assets/c4f122e8-1c04-437b-b177-95535590fb9b)

Please give me advice or share the correct documentation. Thank you.

**Comment by Abdur-rahmaanJ** [comment]
@kuslahne You ran `shopyo initialise`?

**Comment by Abdur-rahmaanJ** [comment]
issue confirmed, fixing!

**Comment by Abdur-rahmaanJ** [comment]
i suggest you upgrade to shopyo==4.12.0 and follow the current readme. Run `flask db migrate and flask db upgrade` if need be
