### ISSUE TITLE
FIX: replace `rundebug/runserver` `shopyo_cli` commands hack with click commands

### ISSUE THREAD

**Issue by rehmanis** [shopyo/shopyo#51]
Replace the `shopyo_cli()` function from [`shopyo/shopyo/api/cli.py`](https://github.com/shopyo/shopyo/blob/dev/shopyo/api/cli.py#L449-L467) with two separate click command as explained below:

- For `rundebug`:
```python
@cli.command("rundebug", with_appcontext=False)
def rundebug():
    """runs the shopyo flask app in development mode"""
    app_path = os.path.join(os.getcwd(), "app.py")

    if not os.path.exists(app_path):
        click.secho(f"Unable to find `app.py` in {os.getcwd()}", fg="red")
        sys.exit(1)

    os.environ["FLASK_APP"] = "app:create_app('development')"
    os.environ["FLASK_ENV"] = "development"
    run(["flask", "run"])
```

- For `runserver`, do the same as above but change `development` to `production` and set command name to `runserver`

- replace `shopyo_cli` with `cli` in both [`/shopyo/shopyo/api/cli.py`](https://github.com/shopyo/shopyo/blob/dev/shopyo/api/cli.py#L471) and [`shopyo/shopyo/manage.py`](https://github.com/shopyo/shopyo/blob/dev/shopyo/manage.py#L10)

To test, run `shopyo rundebug` and `shopyo runserver` in `shopyo/shopyo` directory and go to [`http://127.0.0.1:5000/`](http://127.0.0.1:5000/)

Before starting this issue, make sure you have setup the repo as explained in the docs [here](https://shopyo.readthedocs.io/en/latest/contrib.html#setup-instructions)

**Comment by mahgieeee** [comment]
Hi, may I work on this? It's my first time contributing to open source. Thanks!

**Comment by rehmanis** [comment]
@mahgieeee sure. Let me know if you get stuck anywhere

**Comment by mahgieeee** [comment]
@rehmanis thanks! Will work on it and let you know. Hopefully will be done soon.

**Comment by mahgieeee** [comment]
@rehmanis hi, i made the above revisions. First I ran the shopyo initialise, but there was an error with the @cli command because decorators and function names are the same. Error states that 'function' object has no attribute 'command'. After I put an underscore "_cli" for the function and then ran shopyo initialise, it worked with the shopyo logo popping up and creating databases. http://127.0.0.1:5000/ is not connected after running run shopyo rundebug and shopyo runserver. Please let me know how come it's not connected. Thanks!

**Comment by rehmanis** [comment]
@mahgieeee let talk on discord https://github.com/shopyo/shopyo. Might be easier to help you debug

**Comment by rehmanis** [comment]
So first does the general setup work for you that is when you ran `shopyo initialise` and python `manage.py rundebug` after you do the initial setup and without adding any code?
