### ISSUE TITLE
REFACTOR: move all github images to assets folder

### ISSUE THREAD

**Issue by rehmanis** [shopyo/shopyo#7]
move banner, other images etch to a new `assets` folder

**Comment by NeelPatel31** [comment]
hey, I want to work on this issue, can you tell me which images I have to move to assets folder?

**Comment by Abdur-rahmaanJ** [comment]
@NeelPatel31 

Create a new folder called assets/

Move all images and screenshots over there

Change all image references where needed to reflect tge change

**Comment by NeelPatel31** [comment]
Help me, how do I create pull request contain assets folder ?

**Comment by Abdur-rahmaanJ** [comment]
@NeelPatel31 You can have a look here: https://shopyo.readthedocs.io/en/latest/contrib.html

**Comment by NeelPatel31** [comment]
@Abdur-rahmaanJ check #87 PR.I have created assets folder.
