### ISSUE TITLE
FEAT: Shopyo packages

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopyo#85]
Design a plugins system for Shopyo which will

- load apps when packaged as a module
- load boxes when packaged as a module

This means loading blueprints, templates and collecting static assets.

In sum, it means that installed shopyo packages must work as well as they work in modules/

We'll have a Google meet to better explain the issue.

I have a base to get started with, needs more discussion.

### Requirements

- Know Flask API for extension development (will help)
- Know Python packaging (knowledge of entry point for developing plugin system is a bonus)

or is a Flask user for some 4 - 5 years

## Appreciation

$100 in btc

Currently my time is a bit limited and i appreciate anybody helping out. Since this is a core milestone of the project, i want someone nice to implement it. I tried putting this on bounty source but i cannot set up Metamask. So i'll be transferring it once the issue is closed. I am willing to answer any question. 

## How to apply? 

- Drop a comment: Interested then join the [discord server](https://discord.gg/k37Ef6w). We'll then have a Google meet. If you are still interested, then we'll continue.

**Comment by Abdur-rahmaanJ** [comment]
- Modules blueprints in site-packages are being loaded
- Changing collectstatic command and get_asset to load assets from site-package modules
- Load boxes (group of modules)

**Comment by CheeseCake87** [comment]
ping

**Comment by Abdur-rahmaanJ** [comment]
solved by #119
