### ISSUE TITLE
Add filtering options to the audit command

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopyo#94]
shopyo audit generates something like this:

```
Running audit ...
Checking apps ...
/home/appinv/code/shopyo/shopyo/modules/www
    warning: global.py not found

/home/appinv/code/shopyo/shopyo/modules/resource
    warning: global.py not found

/home/appinv/code/shopyo/shopyo/modules/box__default
    /home/appinv/code/shopyo/shopyo/modules/box__default/settings
        warning: forms.py not found
        warning: global.py not found
    /home/appinv/code/shopyo/shopyo/modules/box__default/dashboard
        warning: forms.py not found
        warning: models.py not found
        warning: global.py not found
    /home/appinv/code/shopyo/shopyo/modules/box__default/auth
        warning: global.py not found
    /home/appinv/code/shopyo/shopyo/modules/box__default/appadmin
        warning: forms.py not found
        warning: global.py not found
    /home/appinv/code/shopyo/shopyo/modules/box__default/base
        warning: forms.py not found
        warning: models.py not found
        warning: global.py not found
    /home/appinv/code/shopyo/shopyo/modules/box__default/theme

/home/appinv/code/shopyo/shopyo/modules/box__bizhelp
    /home/appinv/code/shopyo/shopyo/modules/box__bizhelp/people
        warning: forms.py not found
        warning: global.py not found
    /home/appinv/code/shopyo/shopyo/modules/box__bizhelp/appointment
        warning: forms.py not found
        warning: global.py not found
    /home/appinv/code/shopyo/shopyo/modules/box__bizhelp/contact
    /home/appinv/code/shopyo/shopyo/modules/box__bizhelp/page
        warning: global.py not found

Audit finished!

```

The command is defined [here](https://github.com/shopyo/shopyo/blob/2aa4cf467a6ead735578667b242bec9803d070b5/shopyo/api/cli.py#L511) with the audit [here](https://github.com/shopyo/shopyo/blob/2aa4cf467a6ead735578667b242bec9803d070b5/shopyo/api/cmd_helper.py#L451).

It is cumbersome to view all warnings. We can add flags to filter warnings by severe like --show severe,warning

Task: Add flags to filter warnings. Feel free to modify the code!

**Comment by gsinghly** [comment]
@Abdur-rahmaanJ , I would like to work on this issue. Can you explain a bit about the desired enhancement we want here.

How do we decide which issues are severe, what I believe is all audits with a specific prefix can be clubbed into one flag
i.e.
`shopyo audit --show warning` can output all warnings
`shopyo audit --show info` can output all information
`shopyo audit --show warning info` can output all warnings & information


Let me know, what you think, we can discuss on this. Thanks!

**Comment by Abdur-rahmaanJ** [comment]
@gsinghly Yes, by prefix is one way to go about it, the second way is to rework a bit maybe by a dictionary approach to have severity as key. The proposed commands look great!
